-- ==============================================================================
-- QUERY TITLE       : Depth and Level to Base of Made Ground (Spatially Enabled)
-- AUTHOR / ORG      : Richard Meredith / GeoEnvironmental Consulting Ltd
-- PROJECT / TOOLS   : AGS Tools Project (FOSS)
-- LICENSE           : MIT / Creative Commons CC0 (FOSS-friendly)
-- DIALECT           : SQLite / GeoPackage (Optimized for QGIS)
-- SOURCE TABLES     : GEOL, LOCA
-- DESCRIPTION       :
--   Calculates the maximum base depth and 3D Reduced Level of 'Made Ground' (MG).
--   Generates a dynamic warning message showing the End of Hole (EOH) depth if the 
--   Made Ground was not bottomed.
--
--   SPATIALLY ENABLED: Retains Easting, Northing, Ground Level, and dynamically
--   constructs 3D SpatiaLite Geometry (MakePointZ) using calculated base levels.
--   If the Made Ground was not bottomed, the geometry is set to NULL to prevent
--   unverified boundary intersections from distorting geological models or contours.
--
--   ASSUMPTION: Made Ground is identified on the basis of the 'GEOL_LEG' 
--   code starting with the number '1'.
--
--   TABLE GENERATION AIM:
--   Structured specifically to enable clean data visualization, statistical analysis,
--   and generating plots, contour maps, or 3D thickness models of the Made Ground
--   using QGIS plugins (such as Qgis2threejs or Contour Design).
-- ==============================================================================
-- ⚖️ GNU GPL v3 LICENSE & PROFESSIONAL DISCLAIMER 
-- ==============================================================================
-- Copyright (C) 2026 GeoEnvironmental Consulting Ltd
--
-- This SQL query is free software: you can redistribute it and/or modify
-- it under the terms of the GNU General Public License as published by
-- the Free Software Foundation, version 3 of the License.
--
-- This code is distributed WITHOUT ANY WARRANTY; without even the implied 
-- warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
-- GNU General Public License for more details <https://www.gnu.org/licenses/>.
--
-- TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW:
-- 1. All implied terms, conditions, and warranties—including but not limited to 
--    implied terms of SATISFACTORY QUALITY, FITNESS FOR A PARTICULAR PURPOSE, 
--    and non-infringement of intellectual property—are hereby EXCLUDED.
--
-- 2. The author and GeoEnvironmental Consulting Ltd shall not be liable for any 
--    direct, indirect, incidental, or consequential loss or damage (including 
--    but not limited to site engineering errors, financial loss, business 
--    disruption, or data corruption) arising from the use of, or reliance upon, 
--    the outputs generated by this script.
--
-- 3. PROFESSIONAL RESPONSIBILITY (THE 'ENGAGE BRAIN' DIRECTIVE): 
--    This SQL query is a spatial processing tool, not a crystal ball. 
--    It does not replace professional, qualified human interpretation. Users are 
--    respectfully but firmly reminded to engage their brains (specifically ensuring 
--    cognition is in a forward gear) before executing this script or trusting its 
--    outputs. Trusting automated spatial interpolation blindly is a guaranteed 
--    recipe for causing expensive mistakes.
--
-- NOTHING IN THIS DISCLAIMER SHALL LIMIT OR EXCLUDE LIABILITY FOR:
-- (a) Death or personal injury resulting from negligence;
-- (b) Fraud or fraudulent misrepresentation; or
-- (c) Any other liability which cannot be excluded or limited under the laws of 
--     England and Wales.
-- ==============================================================================


WITH MadeGroundRecords AS (
    -- Filter the GEOL table based on the assumption that codes starting with '1' represent Made Ground
    SELECT 
        G.LOCA_ID,
        CAST(NULLIF(G.GEOL_BASE, '') AS REAL) AS Cleaned_Base
    FROM 
        GEOL G
    WHERE 
        SUBSTR(G.GEOL_LEG, 1, 1) = '1'
)

SELECT 
    -- 1. QGIS Unique Feature Identifier (Mandatory for Virtual Layers and database mapping)
    ROW_NUMBER() OVER () AS fid,

    -- 2. Location & Spatial Identifiers (Robust tabular and geometric coordinate extraction)
    MG.LOCA_ID AS "Exploratory Hole Location",
    COALESCE(CAST(NULLIF(L.LOCA_NATE, '') AS REAL), X(L.geom)) AS "Easting",
    COALESCE(CAST(NULLIF(L.LOCA_NATN, '') AS REAL), Y(L.geom)) AS "Northing",
    CAST(NULLIF(L.LOCA_GL, '') AS REAL) AS "Ground Level (mAOD)",
    
    -- 3. Made Ground Bottom Depths
    MAX(MG.Cleaned_Base) AS "Depth to Base of Made Ground (m)",
    
    -- 4. Calculated Levels (Dual outputs: Text Warning for auditing, Numeric for Plotting/Contouring)
    
    -- Check if the maximum MG base equals or exceeds the total borehole depth (EOH)
    CASE 
        WHEN MAX(MG.Cleaned_Base) >= CAST(NULLIF(L.LOCA_FDEP, '') AS REAL) 
        THEN 'MG not bottomed; > ' || L.LOCA_FDEP
        ELSE CAST(ROUND(CAST(NULLIF(L.LOCA_GL, '') AS REAL) - MAX(MG.Cleaned_Base), 2) AS TEXT)
    END AS "Base Reduced Level (m)",

    -- Clean numeric elevation column to ensure charting software and contour tools do not break on text warnings
    CASE 
        WHEN MAX(MG.Cleaned_Base) >= CAST(NULLIF(L.LOCA_FDEP, '') AS REAL) 
        THEN NULL
        ELSE ROUND(CAST(NULLIF(L.LOCA_GL, '') AS REAL) - MAX(MG.Cleaned_Base), 2)
    END AS "Numeric Base Level (mAOD)",

    -- 5. Status & Quality Tagging
    CASE 
        WHEN MAX(MG.Cleaned_Base) >= CAST(NULLIF(L.LOCA_FDEP, '') AS REAL) 
        THEN 'Uncertain (Not Bottomed)'
        ELSE 'Confirmed Base'
    END AS "Stratum Status",
    
    -- 6. Dynamic 3D Spatial Geometry Construction
    -- Set geom to NULL if the stratum base was not bottomed, as we cannot identify the actual geometry of the boundary.
    -- Otherwise, construct a 3D SpatiaLite geometry point using the calculated Z base level.
    CASE 
        WHEN MAX(MG.Cleaned_Base) >= CAST(NULLIF(L.LOCA_FDEP, '') AS REAL)
        THEN NULL
        ELSE MakePointZ(X(L.geom), Y(L.geom), ROUND(CAST(NULLIF(L.LOCA_GL, '') AS REAL) - MAX(MG.Cleaned_Base), 2), COALESCE(SRID(L.geom), 27700))
    END AS geom

FROM 
    MadeGroundRecords MG

-- Join with the spatial locations table to get coordinates/geometries and ground levels
JOIN 
    loca L ON MG.LOCA_ID = L.LOCA_ID

-- Group by location parameters to correctly aggregate the MAX() depth and math functions per borehole
GROUP BY 
    MG.LOCA_ID, 
    L.geom,
    L.LOCA_GL,
    L.LOCA_FDEP,
    L.LOCA_NATE,
    L.LOCA_NATN;
