-- ==============================================================================
-- QUERY TITLE       : Depth and Level to Rockhead (mAOD) Query
-- AUTHOR / ORG      : Richard Meredith / GeoEnvironmental Consulting Ltd
-- PROJECT / TOOLS   : AGS Tools Project (FOSS)
-- LICENSE           : MIT / Creative Commons CC0 (FOSS-friendly)
-- DIALECT           : SQLite / GeoPackage (Optimized for QGIS)
-- SOURCE TABLES     : GEOL, LOCA
-- DESCRIPTION       :
--   Identifies the shallowest bedrock layer (Rockhead) for each location,
--   extracts its description, depth, and calculates the rockhead level in mAOD
--   by subtracting the depth from the exploratory hole's ground level (LOCA_GL).
--
--   SPATIALLY ENABLED: Retains Easting, Northing, Ground Level, and integrates
--   SpatiaLite geometry.
--
--   ASSUMPTION: Bedrock/Rockhead is identified on the basis of the 'GEOL_LEG' 
--   code starting with the number '8'.
--
--   TABLE GENERATION AIM:
--   Structured specifically to enable clean data visualization, statistical analysis,
--   and generating plots, contour maps, or 3D surface models of the rockhead layer
--   using QGIS plugins (such as Contour Design or Qgis2threejs) or external tools.
-- ==============================================================================
-- ⚖️ GNU GPL v3 LICENSE & PROFESSIONAL DISCLAIMER 
-- ==============================================================================
-- Copyright (C) 2026 GeoEnvironmental Consulting Ltd
--
-- This SQL query is free software: you can redistribute it and/or modify
-- it under the terms of the GNU General Public License as published by
-- the Free Software Foundation, version 3 of the License.
--
-- This code is distributed WITHOUT ANY WARRANTY; without even the implied 
-- warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
-- GNU General Public License for more details <https://www.gnu.org/licenses/>.
--
-- TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW:
-- 1. All implied terms, conditions, and warranties—including but not limited to 
--    implied terms of SATISFACTORY QUALITY, FITNESS FOR A PARTICULAR PURPOSE, 
--    and non-infringement of intellectual property—are hereby EXCLUDED.
--
-- 2. The author and GeoEnvironmental Consulting Ltd shall not be liable for any 
--    direct, indirect, incidental, or consequential loss or damage (including 
--    but not limited to site engineering errors, financial loss, business 
--    disruption, or data corruption) arising from the use of, or reliance upon, 
--    the outputs generated by this script.
--
-- 3. PROFESSIONAL RESPONSIBILITY (THE 'ENGAGE BRAIN' DIRECTIVE): 
--    This SQL query is a spatial processing tool, not a crystal ball. 
--    It does not replace professional, qualified human interpretation. Users are 
--    respectfully but firmly reminded to engage their brains (specifically ensuring 
--    cognition is in a forward gear) before executing this script or trusting its 
--    outputs. Trusting automated spatial interpolation blindly is a guaranteed 
--    recipe for causing expensive mistakes.
--
-- NOTHING IN THIS DISCLAIMER SHALL LIMIT OR EXCLUDE LIABILITY FOR:
-- (a) Death or personal injury resulting from negligence;
-- (b) Fraud or fraudulent misrepresentation; or
-- (c) Any other liability which cannot be excluded or limited under the laws of 
--     England and Wales.
-- ==============================================================================

WITH RankedBedrock AS (
    SELECT 
        G.LOCA_ID,
        -- CAST to REAL (SQLite's float equivalent) and handle potential empty/null text values safely
        CAST(NULLIF(G.GEOL_TOP, '') AS REAL) AS Cleaned_Top,
        G.GEOL_DESC,
        -- Rank the bedrock layers for each borehole from shallowest to deepest to isolate rockhead
        ROW_NUMBER() OVER (
            PARTITION BY G.LOCA_ID 
            ORDER BY CAST(NULLIF(G.GEOL_TOP, '') AS REAL) ASC
        ) AS Row_Rank
    FROM 
        GEOL G
    WHERE 
        -- Filter for records where the geology legend code starts with '8' (representing Bedrock)
        -- Using LIKE '8%' enables index scans in SQLite where applicable
        G.GEOL_LEG LIKE '8%'
)

SELECT 
    -- 1. QGIS Unique Feature Identifier (Mandatory for Virtual Layers and database mapping)
    ROW_NUMBER() OVER () AS fid,

    -- 2. Hole Identifiers & Coordinates
    RB.LOCA_ID AS "Exploratory Hole Location",
    CAST(NULLIF(L.LOCA_NATE, '') AS REAL) AS "Easting",
    CAST(NULLIF(L.LOCA_NATN, '') AS REAL) AS "Northing",
    CAST(NULLIF(L.LOCA_GL, '') AS REAL) AS "Ground Level (mAOD)",
    
    -- 3. Measured Depths and Calculated Levels
    RB.Cleaned_Top AS "Depth to Rockhead (m)",
    
    -- Calculate Rockhead Level (mAOD) = Ground Level (LOCA_GL) - Rockhead Depth (GEOL_TOP)
    -- Using NULLIF handles cases where a borehole ground level wasn't recorded.
    -- ROUND to 2 decimal places keeps the attribute table clean in QGIS.
    ROUND(CAST(NULLIF(L.LOCA_GL, '') AS REAL) - RB.Cleaned_Top, 2) AS "Rockhead Level (mAOD)",
    
    -- 4. Geology Description & Spatials
    RB.GEOL_DESC AS "Description of Rockhead",
    
    -- Include geometry from the loca table so this can be mapped as a spatial layer in QGIS
    L.geom

FROM 
    RankedBedrock RB

-- Join with the spatial locations table to get coordinates/geometries and ground levels
JOIN 
    loca L ON RB.LOCA_ID = L.LOCA_ID

WHERE 
    -- Only pull the absolute shallowest (#1 ranked) bedrock layer per borehole
    RB.Row_Rank = 1;
