-- ==============================================================================
-- QUERY TITLE       : ELRG Complete Soil Contamination Pivot Table (Spatially Enabled)
-- AUTHOR / EMAIL    : Richard Meredith / richard.meredith@geo-env.co.uk
-- ORGANIZATION      : GeoEnvironmental Consulting Ltd
-- PROJECT / TOOLS   : AGS Tools Project (FOSS)
-- LICENSE           : GNU GPL v3 (GPL-compatible open-source)
-- COMPATIBILITY     : QGIS 3.x (SpatiaLite / GeoPackage SQLite Provider)
-- AGS VERSION       : AGS 4.0.x / 4.1.x
-- SOURCE TABLES     : ELRG / LOCA
-- DESCRIPTION       : Aggregates alternative environmental laboratory testing data (ELRG) from vertical rows into a horizontal matrix, reorganizing physical soil samples into single rows with 123 determinand columns mapped to spatial coordinates (Easting, Northing, Elevation) and geometry in QGIS while filtering out liquid units.
-- ==============================================================================

-- ==============================================================================
-- ⚖️ GNU GPL v3 LICENSE & PROFESSIONAL DISCLAIMER 
-- ==============================================================================
-- Copyright (C) 2026 GeoEnvironmental Consulting Ltd
--
-- This SQL query is free software: you can redistribute it and/or modify
-- it under the terms of the GNU General Public License as published by
-- the Free Software Foundation, version 3 of the License.
--
-- This code is distributed WITHOUT ANY WARRANTY; without even the implied 
-- warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
-- GNU General Public License for more details <https://www.gnu.org/licenses/>.
--
-- TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW:
-- 1. All implied terms, conditions, and warranties—including but not limited to 
--    implied terms of SATISFACTORY QUALITY, FITNESS FOR A PARTICULAR PURPOSE, 
--    and non-infringement of intellectual property—are hereby EXCLUDED.
--
-- 2. The author and GeoEnvironmental Consulting Ltd shall not be liable for any 
--    direct, indirect, incidental, or consequential loss or damage (including 
--    but not limited to site engineering errors, financial loss, business 
--    disruption, or data corruption) arising from the use of, or reliance upon, 
--    the outputs generated by this script.
--
-- 3. PROFESSIONAL RESPONSIBILITY (THE 'ENGAGE BRAIN' DIRECTIVE): 
--    This SQL query is a spatial processing tool, not a crystal ball. 
--    It does not replace professional, qualified human interpretation. Users are 
--    respectfully but firmly reminded to engage their brains (specifically ensuring 
--    cognition is in a forward gear) before executing this script or trusting its 
--    outputs. Trusting automated spatial interpolation blindly is a guaranteed 
--    recipe for causing expensive mistakes.
--
-- NOTHING IN THIS DISCLAIMER SHALL LIMIT OR EXCLUDE LIABILITY FOR:
-- (a) Death or personal injury resulting from negligence;
-- (b) Fraud or fraudulent misrepresentation; or
-- (c) Any other liability which cannot be excluded or limited under the laws of 
--     England and Wales.
-- ==============================================================================

SELECT 
    -- QGIS Unique Feature Identifier (Allows clicking/identifying features on map)
    ROW_NUMBER() OVER () AS fid,

    -- 1. Concatenated Unique Sample Identifier (Excel Lookup Key)
    COALESCE(NULLIF(E.LOCA_ID, ''), '-')   || '_' || 
    COALESCE(NULLIF(E.SAMP_TOP, ''), '-')  || '_' || 
    COALESCE(NULLIF(E.SAMP_TYPE, ''), '-') || '_' || 
    COALESCE(NULLIF(E.SAMP_REF, ''), '-')  AS "Unique Sample Identifier",

    -- 2. Hole Location & Spatial Identifiers (RESTORED SPATIAL COLUMNS)
    E.LOCA_ID AS "Exploratory Hole Location",
    CAST(NULLIF(L.LOCA_NATE, '') AS REAL) AS "Easting",
    CAST(NULLIF(L.LOCA_NATN, '') AS REAL) AS "Northing",
    CAST(NULLIF(L.LOCA_GL, '') AS REAL) AS "Ground Level (mAOD)",
    CAST(NULLIF(E.SAMP_TOP, '') AS REAL) AS "Sample Depth Top (m)",
    
    -- Dynamic Level calculation: Z = Ground Elevation - Sample Depth (Rounded to 2 decimal places)
    ROUND(CAST(NULLIF(L.LOCA_GL, '') AS REAL) - CAST(NULLIF(E.SAMP_TOP, '') AS REAL), 2) AS "Sample Top Elevation (mAOD)",

-- STREAMING_CHUNK: Pivoting ELRG metals and speciated chromium...
    -- 3. Pivoted Metals Columns (Ordered exactly as per Column B of your Screening Sheet)
    -- Mapping combines standard CAS Codes (ELRG_CODE) and text variations (ELRG_NAME)
    
    -- (1) Arsenic
    MAX(CASE WHEN E.ELRG_CODE = '7440-38-2' OR E.ELRG_NAME LIKE '%Arsenic%' THEN E.ELRG_RTXT END) AS "Arsenic",
    
    -- (2) Beryllium
    MAX(CASE WHEN E.ELRG_CODE = '7440-41-7' OR E.ELRG_NAME LIKE '%Beryllium%' THEN E.ELRG_RTXT END) AS "Beryllium",
    
    -- (3) Boron
    MAX(CASE WHEN E.ELRG_CODE = '7440-42-8' OR E.ELRG_NAME LIKE '%Boron%' THEN E.ELRG_RTXT END) AS "Boron",
    
    -- (4) Cadmium
    MAX(CASE WHEN E.ELRG_CODE = '7440-43-9' OR E.ELRG_NAME LIKE '%Cadmium%' THEN E.ELRG_RTXT END) AS "Cadmium",
    
    -- (5) Chromium (trivalent) / Total Chromium
    MAX(CASE WHEN E.ELRG_CODE = '7440-47-3' OR (E.ELRG_NAME LIKE '%Chromium%' AND E.ELRG_NAME NOT LIKE '%Hexa%') THEN E.ELRG_RTXT END) AS "Chromium (trivalent)",
    
    -- (6) Chromium (hexavalent)
    MAX(CASE WHEN E.ELRG_CODE = '18540-29-9' OR E.ELRG_NAME LIKE '%Chromium%Hexa%' OR E.ELRG_NAME LIKE '%Hexavalent%Chromium%' THEN E.ELRG_RTXT END) AS "Chromium (hexavalent)",
    
    -- (7) Copper
    MAX(CASE WHEN E.ELRG_CODE = '7440-50-8' OR E.ELRG_NAME LIKE '%Copper%' THEN E.ELRG_RTXT END) AS "Copper",
    
    -- (8) Lead
    MAX(CASE WHEN E.ELRG_CODE = '7439-92-1' OR E.ELRG_NAME LIKE '%Lead%' THEN E.ELRG_RTXT END) AS "Lead",
    
    -- (9) Mercury (elemental)
    MAX(CASE WHEN E.ELRG_NAME LIKE '%Mercury%elemental%' THEN E.ELRG_RTXT END) AS "Mercury (elemental)",
    
    -- (10) Mercury (inorganic) - standard lab 'Mercury' matches here
    MAX(CASE WHEN E.ELRG_CODE = '7439-97-6' OR (E.ELRG_NAME LIKE '%Mercury%' AND E.ELRG_NAME NOT LIKE '%elemental%' AND E.ELRG_NAME NOT LIKE '%Methyl%') THEN E.ELRG_RTXT END) AS "Mercury (inorganic)",
    
    -- (11) Methylmercury
    MAX(CASE WHEN E.ELRG_NAME LIKE '%Methylmercury%' THEN E.ELRG_RTXT END) AS "Methylmercury",
    
    -- (12) Nickel
    MAX(CASE WHEN E.ELRG_CODE = '7440-02-0' OR E.ELRG_NAME LIKE '%Nickel%' THEN E.ELRG_RTXT END) AS "Nickel",
    
    -- (13) Selenium
    MAX(CASE WHEN E.ELRG_CODE = '7782-49-2' OR E.ELRG_NAME LIKE '%Selenium%' THEN E.ELRG_RTXT END) AS "Selenium",
    
    -- (14) Vanadium
    MAX(CASE WHEN E.ELRG_CODE = '7440-62-2' OR E.ELRG_NAME LIKE '%Vanadium%' THEN E.ELRG_RTXT END) AS "Vanadium",
    
    -- (15) Zinc
    MAX(CASE WHEN E.ELRG_CODE = '7440-66-6' OR E.ELRG_NAME LIKE '%Zinc%' THEN E.ELRG_RTXT END) AS "Zinc",

-- STREAMING_CHUNK: Pivoting ELRG BTEX compounds...
    -- 4. Pivoted BTEX Columns (Ordered exactly as per Column B of your Screening Sheet)
    
    -- (16) Benzene
    MAX(CASE WHEN E.ELRG_CODE = '71-43-2' OR E.ELRG_NAME = 'Benzene' THEN E.ELRG_RTXT END) AS "Benzene",
    
    -- (17) Toluene (Safely skips 'Toluene-D8' surrogate)
    MAX(CASE WHEN E.ELRG_CODE = '108-88-3' OR E.ELRG_NAME = 'Toluene' THEN E.ELRG_RTXT END) AS "Toluene",
    
    -- (18) Ethylbenzene
    MAX(CASE WHEN E.ELRG_CODE = '100-41-4' OR E.ELRG_NAME IN ('o-Xylene', 'o-xylene') OR E.ELRG_NAME = 'Ethylbenzene' THEN E.ELRG_RTXT END) AS "Ethylbenzene",
    
    -- (19) O – Xylene
    MAX(CASE WHEN E.ELRG_CODE = '95-47-6' OR E.ELRG_NAME IN ('o-Xylene', 'o-xylene') THEN E.ELRG_RTXT END) AS "O – Xylene",
    
    -- (20) M – Xylene (Commonly reported combined with Para-xylene as 'm,p xylenes' in lab data)
    MAX(CASE WHEN E.ELRG_CODE = 'P1374' OR E.ELRG_NAME IN ('m,p xylenes', 'm,p-Xylene') THEN E.ELRG_RTXT END) AS "M – Xylene",
    
    -- (21) P – Xylene (Empty/Null placeholder if reported combined above, otherwise populated if split)
    MAX(CASE WHEN E.ELRG_NAME = 'p-Xylene' THEN E.ELRG_RTXT END) AS "P – Xylene",

-- STREAMING_CHUNK: Pivoting ELRG PAHs...
    -- 5. Pivoted Polycyclic Aromatic Hydrocarbons (PAHs)
    -- Column names match spreadsheet layout exactly, mimicking trailing spaces where present
    
    -- (22) Acenaphthene
    MAX(CASE WHEN E.ELRG_CODE = '83-32-9' OR E.ELRG_NAME = 'Acenaphthene' THEN E.ELRG_RTXT END) AS "Acenaphthene ",
    
    -- (23) Acenaphthylene
    MAX(CASE WHEN E.ELRG_CODE = '208-96-8' OR E.ELRG_NAME = 'Acenaphthylene' THEN E.ELRG_RTXT END) AS "Acenaphthylene ",
    
    -- (24) Anthracene
    MAX(CASE WHEN E.ELRG_CODE = '120-12-7' OR E.ELRG_NAME = 'Anthracene' THEN E.ELRG_RTXT END) AS "Anthracene ",
    
    -- (25) Benz(a)anthracene
    MAX(CASE WHEN E.ELRG_CODE = '56-55-3' OR E.ELRG_NAME IN ('Benzo(a)anthracene', 'Benz(a)anthracene') THEN E.ELRG_RTXT END) AS "Benz(a)anthracene ",
    
    -- (26) Benzo(a)pyrene (Bap)
    MAX(CASE WHEN E.ELRG_CODE = '50-32-8' OR E.ELRG_NAME IN ('Benzo(a)pyrene', 'Benzo[a]pyrene') THEN E.ELRG_RTXT END) AS "Benzo(a)pyrene (Bap) ",
    
    -- (27) Benzo(b)fluoranthene
    MAX(CASE WHEN E.ELRG_CODE = '205-99-2' OR E.ELRG_NAME = 'Benzo(b)fluoranthene' THEN E.ELRG_RTXT END) AS "Benzo(b)fluoranthene ",
    
    -- (28) Benzo(g,h,i)perylene (Catches 'Benzo(ghi)perylene' spelling variations)
    MAX(CASE WHEN E.ELRG_CODE = '191-24-2' OR E.ELRG_NAME IN ('Benzo (g,h,i) perylene', 'Benzo(g,h,i)perylene', 'Benzo(ghi)perylene', 'Benzo (ghi) perylene') THEN E.ELRG_RTXT END) AS "Benzo(g,h,i)perylene ",
    
    -- (29) Benzo(k)fluoranthene
    MAX(CASE WHEN E.ELRG_CODE = '207-08-9' OR E.ELRG_NAME = 'Benzo(k)fluoranthene' THEN E.ELRG_RTXT END) AS "Benzo(k)fluoranthene ",
    
    -- (30) Chrysene (Safely skips 'Chrysene-d12' surrogate)
    MAX(CASE WHEN E.ELRG_CODE = '218-01-9' OR E.ELRG_NAME = 'Chrysene' THEN E.ELRG_RTXT END) AS "Chrysene ",
    
    -- (31) Dibenzo(ah)anthracene
    MAX(CASE WHEN E.ELRG_CODE = '53-70-3' OR E.ELRG_NAME IN ('Dibenzo(ah)anthracene', 'Dibenz(a,h)anthracene', 'Dibenz-a-h-anthracene') THEN E.ELRG_RTXT END) AS "Dibenzo(ah)anthracene ",
    
    -- (32) Fluoranthene
    MAX(CASE WHEN E.ELRG_CODE = '206-44-0' OR E.ELRG_NAME = 'Fluoranthene' THEN E.ELRG_RTXT END) AS "Fluoranthene ",
    
    -- (33) Fluorene
    MAX(CASE WHEN E.ELRG_CODE = '86-73-7' OR E.ELRG_NAME = 'Fluorene' THEN E.ELRG_RTXT END) AS "Fluorene ",
    
    -- (34) Indeno(1,2,3-cd)pyrene
    MAX(CASE WHEN E.ELRG_CODE = '193-39-5' OR E.ELRG_NAME = 'Indeno(1,2,3-cd)pyrene' THEN E.ELRG_RTXT END) AS "Indeno(1,2,3-cd)pyrene ",
    
    -- (35) Naphthalene (Safely skips 'Naphthalene-d8' surrogate and resolves lab spelling variant 'Napthalene')
    MAX(CASE WHEN E.ELRG_CODE = '91-20-3' OR E.ELRG_NAME IN ('Naphthalene', 'Napthalene') THEN E.ELRG_RTXT END) AS "Naphthalene",
    
    -- (36) Phenanthrene (Safely skips 'Phenanthrene-d10' surrogate)
    MAX(CASE WHEN E.ELRG_CODE = '85-01-8' OR E.ELRG_NAME = 'Phenanthrene' THEN E.ELRG_RTXT END) AS "Phenanthrene ",
    
    -- (37) Pyrene
    MAX(CASE WHEN E.ELRG_CODE = '129-00-0' OR E.ELRG_NAME = 'Pyrene' THEN E.ELRG_RTXT END) AS "Pyrene ",
    
    -- (38) Coal Tar (Bap as surrogate marker)
    MAX(CASE WHEN E.ELRG_CODE = '50-32-8' OR E.ELRG_NAME IN ('Benzo(a)pyrene', 'Benzo[a]pyrene') THEN E.ELRG_RTXT END) AS "Coal Tar (Bap as surrogate marker) ",

-- STREAMING_CHUNK: Pivoting ELRG explosives...
    -- 6. Pivoted Explosive Compounds (Placed exactly between PAHs and TPHs as per your Soil Screening Sheet)
    
    -- (39) 2, 4, 6 Trinitrotoluene
    MAX(CASE WHEN E.ELRG_CODE = '118-96-7' OR E.ELRG_NAME LIKE '%Trinitrotoluene%' OR E.ELRG_NAME LIKE '%TNT%' THEN E.ELRG_RTXT END) AS "2, 4, 6 Trinitrotoluene ",
    
    -- (40) RDX (Royal Demolition Explosive C3H6N6O6)
    MAX(CASE WHEN E.ELRG_CODE = '121-82-4' OR E.ELRG_NAME LIKE '%RDX%' OR E.ELRG_NAME LIKE '%Cyclotrimethylenetrinitramine%' THEN E.ELRG_RTXT END) AS "RDX (Royal Demolition Explosive C3H6N6O6) ",
    
    -- (41) HMX (High Melting Explosive C4H8N8O8)
    MAX(CASE WHEN E.ELRG_CODE = '2691-41-0' OR E.ELRG_NAME LIKE '%HMX%' OR E.ELRG_NAME LIKE '%Cyclotetramethylenetetranitramine%' THEN E.ELRG_RTXT END) AS "HMX (High Melting Explosive C4H8N8O8) ",

-- STREAMING_CHUNK: Pivoting ELRG TPH fractions...
    -- 7. Pivoted Petroleum Hydrocarbons (TPH Fractions)
    -- Ordered exactly as per Column B of your Screening Sheet
    
    -- (42) Aliphatic EC 5-6
    MAX(CASE WHEN E.ELRG_CODE = 'P1407' OR E.ELRG_NAME LIKE '%Aliphatics%C5-6%' THEN E.ELRG_RTXT END) AS "Aliphatic EC 5-6 ",
    
    -- (43) Aliphatic EC >6-8
    MAX(CASE WHEN E.ELRG_CODE = 'P1408' OR E.ELRG_NAME LIKE '%Aliphatics%C6-8%' THEN E.ELRG_RTXT END) AS "Aliphatic EC >6-8 ",
    
    -- (44) Aliphatic EC >8-10
    MAX(CASE WHEN E.ELRG_CODE = 'P1409' OR E.ELRG_NAME LIKE '%Aliphatics%C8-10%' THEN E.ELRG_RTXT END) AS "Aliphatic EC >8-10 ",
    
    -- (45) Aliphatic EC >10-12
    MAX(CASE WHEN E.ELRG_CODE = 'P1410' OR E.ELRG_NAME LIKE '%Aliphatics%C10-12%' THEN E.ELRG_RTXT END) AS "Aliphatic EC >10-12 ",
    
    -- (46) Aliphatic EC >12-16
    MAX(CASE WHEN E.ELRG_CODE = 'P1411' OR E.ELRG_NAME LIKE '%Aliphatics%C12-16%' THEN E.ELRG_RTXT END) AS "Aliphatic EC >12-16 ",
    
    -- (47) Aliphatic EC >16-35 (Intelligent numeric sum of laboratory Aliphatics >C16-21 and >C21-35)
    CASE WHEN MAX(CASE WHEN E.ELRG_CODE IN ('P1412', 'P1413') THEN E.ELRG_RTXT END) IS NOT NULL THEN
        ROUND(
            COALESCE(CAST(REPLACE(MAX(CASE WHEN E.ELRG_CODE = 'P1412' THEN E.ELRG_RTXT END), '<', '') AS REAL), 0) +
            COALESCE(CAST(REPLACE(MAX(CASE WHEN E.ELRG_CODE = 'P1413' THEN E.ELRG_RTXT END), '<', '') AS REAL), 0),
            2
        )
    ELSE NULL END AS "Aliphatic EC >16-35 ",
    
    -- (48) Aliphatic EC >35-44
    MAX(CASE WHEN E.ELRG_CODE = 'P1415' OR E.ELRG_NAME LIKE '%Aliphatics%C35-44%' THEN E.ELRG_RTXT END) AS "Aliphatic EC >35-44",

-- STREAMING_CHUNK: Pivoting ELRG aromatics...
    -- (49) Aromatic EC 5-7 (benzene)
    MAX(CASE WHEN E.ELRG_CODE = 'P1354' OR E.ELRG_NAME LIKE '%Aromatics%C6-7%' THEN E.ELRG_RTXT END) AS "Aromatic EC 5-7 (benzene) ",
    
    -- (50) Aromatic EC >7-8 (toluene)
    MAX(CASE WHEN E.ELRG_CODE = 'P1355' OR E.ELRG_NAME LIKE '%Aromatics%C7-8%' THEN E.ELRG_RTXT END) AS "Aromatic EC >7-8 (toluene) ",
    
    -- (51) Aromatic EC >8-10
    MAX(CASE WHEN E.ELRG_CODE = 'P1356' OR E.ELRG_NAME LIKE '%Aromatics%C8-10%' THEN E.ELRG_RTXT END) AS "Aromatic EC >8-10 ",
    
    -- (52) Aromatic EC >10-12
    MAX(CASE WHEN E.ELRG_CODE = 'P1357' OR E.ELRG_NAME LIKE '%Aromatics%C10-12%' THEN E.ELRG_RTXT END) AS "Aromatic EC >10-12 ",
    
    -- (53) Aromatic EC >12-16
    MAX(CASE WHEN E.ELRG_CODE = 'P1358' OR E.ELRG_NAME LIKE '%Aromatics%C12-16%' THEN E.ELRG_RTXT END) AS "Aromatic EC >12-16 ",
    
    -- (54) Aromatic EC >16-21
    MAX(CASE WHEN E.ELRG_CODE = 'P1359' OR E.ELRG_NAME LIKE '%Aromatics%C16-21%' THEN E.ELRG_RTXT END) AS "Aromatic EC >16-21",
    
    -- (55) Aromatic EC >21-35
    MAX(CASE WHEN E.ELRG_CODE = 'P1360' OR E.ELRG_NAME LIKE '%Aromatics%C21-35%' THEN E.ELRG_RTXT END) AS "Aromatic EC >21-35",
    
    -- (56) Aromatic EC >35-44
    MAX(CASE WHEN E.ELRG_CODE = 'P1362' OR E.ELRG_NAME LIKE '%Aromatics%C35-44%' THEN E.ELRG_RTXT END) AS "Aromatic EC >35-44",
    
    -- (57) Aliphatic+Aromatic EC >44-70 (Spacer/Null placeholder column to keep column alignment for copy-pasting)
    NULL AS "Aliphatic+Aromatic   EC >44-70",

-- STREAMING_CHUNK: Pivoting ELRG Chloroalkanes...
    -- 8. Pivoted Chloroalkanes & Chloroalkenes (Ordered exactly as per Column B of your Screening Sheet)
    
    -- (58) 1,2-Dichloroethane
    MAX(CASE WHEN E.ELRG_CODE = '107-06-2' OR E.ELRG_NAME = '1,2-dichloroethane' THEN E.ELRG_RTXT END) AS "1,2-Dichloroethane ",
    
    -- (59) 1,1,1 Trichloroethane (TCA)
    MAX(CASE WHEN E.ELRG_CODE = '71-55-6' OR E.ELRG_NAME = '1,1,1-trichloroethane' THEN E.ELRG_RTXT END) AS "1,1,1 Trichloroethane (TCA) ",
    
    -- (60) 1,1,1,2 Tetrachloroethane
    MAX(CASE WHEN E.ELRG_CODE = '630-20-6' OR E.ELRG_NAME = '1,1,1,2-tetrachloroethane' THEN E.ELRG_RTXT END) AS "1,1,1,2 Tetrachloroethane  ",
    
    -- (61) 1,1,2,2 Tetrachloroethane
    MAX(CASE WHEN E.ELRG_CODE = '79-34-5' OR E.ELRG_NAME = '1,1,2,2-tetrachloroethane' THEN E.ELRG_RTXT END) AS "1,1,2,2 Tetrachloroethane  ",
    
    -- (62) Tetrachloroethene (PCE)
    MAX(CASE WHEN E.ELRG_CODE = '127-18-4' OR E.ELRG_NAME = 'Tetrachloroethene' THEN E.ELRG_RTXT END) AS "Tetrachloroethene (PCE) ",
    
    -- (63) Tetrachloromethane (Carbon Tetrachloride)
    MAX(CASE WHEN E.ELRG_CODE = '56-23-5' OR E.ELRG_NAME = 'Carbon tetrachloride' THEN E.ELRG_RTXT END) AS "Tetrachloromethane  (Carbon Tetrachloride)  ",
    
    -- (64) Trichloroethene (TCE)
    MAX(CASE WHEN E.ELRG_CODE = '79-01-6' OR E.ELRG_NAME = 'Trichloroethene' THEN E.ELRG_RTXT END) AS "Trichloroethene (TCE) ",
    
    -- (65) Trichloromethane (Chloroform)
    MAX(CASE WHEN E.ELRG_CODE = '67-66-3' OR E.ELRG_NAME = 'Chloroform' THEN E.ELRG_RTXT END) AS "Trichloromethane (Chloroform) ",
    
    -- (66) Chloroethene (Vinyl Chloride)
    MAX(CASE WHEN E.ELRG_CODE = '75-01-4' OR E.ELRG_NAME = 'Vinyl chloride' THEN E.ELRG_RTXT END) AS "Chloroethene  (Vinyl Chloride) ",

-- STREAMING_CHUNK: Pivoting ELRG Halogenated Hydrocarbons...
    -- 9. Pivoted Halogenated HCs
    
    -- (67) 1,1,2 Trichloroethane
    MAX(CASE WHEN E.ELRG_CODE = '79-00-5' OR E.ELRG_NAME = '1,1,2-trichloroethane' THEN E.ELRG_RTXT END) AS "1,1,2 Trichloroethane ",
    
    -- (68) 1,1-Dichloroethane
    MAX(CASE WHEN E.ELRG_CODE = '75-34-3' OR E.ELRG_NAME = '1,1-dichloroethane' THEN E.ELRG_RTXT END) AS "1,1-Dichloroethane ",
    
    -- (69) 1,1-Dichloroethene
    MAX(CASE WHEN E.ELRG_CODE = '75-35-4' OR E.ELRG_NAME = '1,1-dichloroethene' THEN E.ELRG_RTXT END) AS "1,1-Dichloroethene ",
    
    -- (70) 1,2-Dichloropropane
    MAX(CASE WHEN E.ELRG_CODE = '78-87-5' OR E.ELRG_NAME = '1,2-dichloropropane' THEN E.ELRG_RTXT END) AS "1,2-Dichloropropane ",
    
    -- (71) 2-Chloronaphthalene
    MAX(CASE WHEN E.ELRG_CODE = '91-58-7' OR E.ELRG_NAME = '2-Chloronaphthalene' THEN E.ELRG_RTXT END) AS "2-Chloronaphthalene ",
    
    -- (72) Bromobenzene
    MAX(CASE WHEN E.ELRG_CODE = '108-86-1' OR E.ELRG_NAME = 'Bromobenzene' THEN E.ELRG_RTXT END) AS "Bromobenzene ",
    
    -- (73) Bromodichloromethane
    MAX(CASE WHEN E.ELRG_CODE = '75-27-4' OR E.ELRG_NAME = 'Bromodichloromethane' THEN E.ELRG_RTXT END) AS "Bromodichloromethane ",
    
    -- (74) Bromoform
    MAX(CASE WHEN E.ELRG_CODE = '75-25-2' OR E.ELRG_NAME = 'Bromoform' THEN E.ELRG_RTXT END) AS "Bromoform ",
    
    -- (75) Chloroethane
    MAX(CASE WHEN E.ELRG_CODE = '75-00-3' OR E.ELRG_NAME = 'Chloroethane' THEN E.ELRG_RTXT END) AS "Chloroethane ",
    
    -- (76) Chloromethane
    MAX(CASE WHEN E.ELRG_CODE = '74-87-3' OR E.ELRG_NAME = 'Chloromethane' THEN E.ELRG_RTXT END) AS "Chloromethane ",
    
    -- (77) cis-1,2 Dichloroethene
    MAX(CASE WHEN E.ELRG_CODE = '156-59-2' OR E.ELRG_NAME = 'cis-1,2-dichloroethene' THEN E.ELRG_RTXT END) AS "cis-1,2 Dichloroethene  ",
    
    -- (78) trans-1,2 Dichloroethene
    MAX(CASE WHEN E.ELRG_CODE = '156-60-5' OR E.ELRG_NAME = 'trans-1,2-dichloroethene' THEN E.ELRG_RTXT END) AS "trans-1,2 Dichloroethene  ",
    
    -- (79) Dichloromethane
    MAX(CASE WHEN E.ELRG_CODE = '75-09-2' OR E.ELRG_NAME = 'Dichloromethane' THEN E.ELRG_RTXT END) AS "Dichloromethane  ",
    
    -- (80) Hexachloroethane
    MAX(CASE WHEN E.ELRG_CODE = '67-72-1' OR E.ELRG_NAME = 'Hexachloroethane' THEN E.ELRG_RTXT END) AS "Hexachloroethane ",

-- STREAMING_CHUNK: Pivoting ELRG Phenols and Chlorophenols...
    -- 10. Pivoted Phenols & Chlorophenols
    
    -- (81) Phenol
    MAX(CASE WHEN E.ELRG_CODE = '108-95-2' OR E.ELRG_NAME = 'Phenol' THEN E.ELRG_RTXT END) AS "Phenol",
    
    -- (82) Chlorophenols (excluding PCP) - Intelligent sum of individual chlorophenols detected in ELRG
    CASE WHEN MAX(CASE WHEN E.ELRG_CODE IN ('120-83-2', '88-06-2', '95-57-8', '95-95-4') THEN E.ELRG_RTXT END) IS NOT NULL THEN
        ROUND(
            COALESCE(CAST(REPLACE(MAX(CASE WHEN E.ELRG_CODE = '120-83-2' THEN E.ELRG_RTXT END), '<', '') AS REAL), 0) +
            COALESCE(CAST(REPLACE(MAX(CASE WHEN E.ELRG_CODE = '88-06-2' THEN E.ELRG_RTXT END), '<', '') AS REAL), 0) +
            COALESCE(CAST(REPLACE(MAX(CASE WHEN E.ELRG_CODE = '95-57-8' THEN E.ELRG_RTXT END), '<', '') AS REAL), 0) +
            COALESCE(CAST(REPLACE(MAX(CASE WHEN E.ELRG_CODE = '95-95-4' THEN E.ELRG_RTXT END), '<', '') AS REAL), 0),
            2
        )
    ELSE NULL END AS "Chlorophenols  (excluding PCP)",
    
    -- (83) Pentachlorophenol (PCP)
    MAX(CASE WHEN E.ELRG_CODE = '87-86-5' OR E.ELRG_NAME = 'Pentachlorophenol (PCP)' THEN E.ELRG_RTXT END) AS "Pentachlorophenol (PCP) ",
    
    -- (84) 2,4-Dimethylphenol
    MAX(CASE WHEN E.ELRG_CODE = '105-67-9' OR E.ELRG_NAME = '2,4-Dimethylphenol' THEN E.ELRG_RTXT END) AS "2,4-Dimethylphenol ",
    
    -- (85) Total Cresols (2-, 3- and 4-methylphenol) - maps standard total cresols
    MAX(CASE WHEN E.ELRG_CODE = 'P2098' OR E.ELRG_NAME IN ('Cresols', 'Total Cresols') THEN E.ELRG_RTXT END) AS "Total Cresols (2-,  3- and  4-methylphenol)",

    -- 11. Pivoted Other Organic Compounds
    
    -- (86) Carbon Disulphide
    MAX(CASE WHEN E.ELRG_CODE = '75-15-0' OR E.ELRG_NAME = 'Carbon disulfide' THEN E.ELRG_RTXT END) AS "Carbon Disulphide  ",
    
    -- (87) Hexachlorobutadiene (HCBD)
    MAX(CASE WHEN E.ELRG_CODE = '87-68-3' OR E.ELRG_NAME = 'Hexachlorobutadiene' THEN E.ELRG_RTXT END) AS "Hexachlorobutadiene (HCBD) ",
    
    -- (88) Biphenyl
    MAX(CASE WHEN E.ELRG_CODE = '92-52-4' OR E.ELRG_NAME = 'Biphenyl' THEN E.ELRG_RTXT END) AS "Biphenyl ",
    
    -- (89) 2,4-Dinitrotoluene
    MAX(CASE WHEN E.ELRG_CODE = '121-14-2' OR E.ELRG_NAME = '2,4-Dinitrotoluene' THEN E.ELRG_RTXT END) AS "2,4-Dinitrotoluene ",
    
    -- (90) 2,6-Dinitrotoluene
    MAX(CASE WHEN E.ELRG_CODE = '606-20-2' OR E.ELRG_NAME = '2,6-Dinitrotoluene' THEN E.ELRG_RTXT END) AS "2,6-Dinitrotoluene ",
    
    -- (91) Tributyl tin oxide
    MAX(CASE WHEN E.ELRG_CODE = '56-35-9' OR E.ELRG_NAME LIKE '%Tributyl tin%' OR E.ELRG_NAME LIKE '%TBTO%' THEN E.ELRG_RTXT END) AS "Tributyl tin oxide ",
    
    -- (92) Methyl tert-butyl ether (MTBE)
    MAX(CASE WHEN E.ELRG_CODE = '1634-04-4' OR E.ELRG_NAME = 'Methyl tert-butyl ether (MTBE)' THEN E.ELRG_RTXT END) AS "Methyl tert-butyl ether (MTBE)",

-- STREAMING_CHUNK: Pivoting ELRG Pesticides...
    -- 12. Pivoted Pesticides
    
    -- (93) Aldrin
    MAX(CASE WHEN E.ELRG_CODE = '309-00-2' OR E.ELRG_NAME = 'Aldrin' THEN E.ELRG_RTXT END) AS "Aldrin ",
    
    -- (94) Atrazine
    MAX(CASE WHEN E.ELRG_CODE = '1912-24-9' OR E.ELRG_NAME = 'Atrazine' THEN E.ELRG_RTXT END) AS "Atrazine ",
    
    -- (95) Dichlorvos
    MAX(CASE WHEN E.ELRG_CODE = '62-73-7' OR E.ELRG_NAME = 'Dichlorvos' THEN E.ELRG_RTXT END) AS "Dichlorvos ",
    
    -- (96) Dieldrin
    MAX(CASE WHEN E.ELRG_CODE = '60-57-1' OR E.ELRG_NAME = 'Dieldrin' THEN E.ELRG_RTXT END) AS "Dieldrin ",
    
    -- (97) Alpha - Endosulfan
    MAX(CASE WHEN E.ELRG_CODE = '959-98-8' OR E.ELRG_NAME LIKE '%Alpha%Endosulfan%' THEN E.ELRG_RTXT END) AS "Alpha - Endosulfan ",
    
    -- (98) Beta - Endosulfan
    MAX(CASE WHEN E.ELRG_CODE = '33213-65-9' OR E.ELRG_NAME LIKE '%Beta%Endosulfan%' THEN E.ELRG_RTXT END) AS "Beta - Endosulfan ",
    
    -- (99) Alpha-Hexachlorocyclohexane
    MAX(CASE WHEN E.ELRG_CODE = '319-84-6' OR E.ELRG_NAME LIKE '%alpha-HCH%' OR E.ELRG_NAME LIKE '%alpha-hexachlorocyclohexane%' THEN E.ELRG_RTXT END) AS "Alpha-Hexachlorocyclohexane ",
    
    -- (100) Beta - Hexachlorocyclohexane
    MAX(CASE WHEN E.ELRG_CODE = '319-85-7' OR E.ELRG_NAME LIKE '%beta-HCH%' OR E.ELRG_NAME LIKE '%beta-hexachlorocyclohexane%' THEN E.ELRG_RTXT END) AS "Beta - Hexachlorocyclohexane ",
    
    -- (101) Gamma – Hexachlorocyclohexane
    MAX(CASE WHEN E.ELRG_CODE = '58-89-9' OR E.ELRG_NAME LIKE '%gamma-HCH%' OR E.ELRG_NAME LIKE '%Lindane%' OR E.ELRG_NAME LIKE '%gamma-hexachlorocyclohexane%' THEN E.ELRG_RTXT END) AS "Gamma – Hexachlorocyclohexane  ",

-- STREAMING_CHUNK: Pivoting ELRG Phthalates...
    -- 13. Pivoted Phthalates (Spelled "Phthaltes" to mirror the screening sheet perfectly)
    
    -- (102) Bis (2-ethylhexyl) phthalate
    MAX(CASE WHEN E.ELRG_CODE = '117-81-7' OR E.ELRG_NAME = 'Bis(2-ethylhexyl)phthalate' THEN E.ELRG_RTXT END) AS "Bis (2-ethylhexyl) phthalate ",
    
    -- (103) Butyl benzyl phthalate
    MAX(CASE WHEN E.ELRG_CODE = '85-68-7' OR E.ELRG_NAME = 'Butylbenzylphthalate' THEN E.ELRG_RTXT END) AS "Butyl benzyl phthalate ",
    
    -- (104) Diethyl Phthalate
    MAX(CASE WHEN E.ELRG_CODE = '84-66-2' OR E.ELRG_NAME = 'Diethylphthalate' THEN E.ELRG_RTXT END) AS "Diethyl Phthalate ",
    
    -- (105) Di-n-butyl phthalate
    MAX(CASE WHEN E.ELRG_CODE = '84-74-2' OR E.ELRG_NAME = 'Di-n-butyl phthalate' THEN E.ELRG_RTXT END) AS "Di-n-butyl phthalate ",
    
    -- (106) Di-n-octyl phthalate
    MAX(CASE WHEN E.ELRG_CODE = '117-84-0' OR E.ELRG_NAME = 'Di-n-octyl phthalate' THEN E.ELRG_RTXT END) AS "Di-n-octyl phthalate ",

-- STREAMING_CHUNK: Pivoting ELRG Aromatic Hydrocarbons...
    -- 14. Pivoted Aromatic HCs
    
    -- (107) 1,2,4-Trimethylbenzene
    MAX(CASE WHEN E.ELRG_CODE = '95-63-6' OR E.ELRG_NAME = '1,2,4-trimethylbenzene' THEN E.ELRG_RTXT END) AS "1,2,4-Trimethylbenzene ",
    
    -- (108) Isopropylbenzene
    MAX(CASE WHEN E.ELRG_CODE = '98-82-8' OR E.ELRG_NAME = 'Isopropylbenzene' THEN E.ELRG_RTXT END) AS "Isopropylbenzene ",
    
    -- (109) Propylbenzene
    MAX(CASE WHEN E.ELRG_CODE = '103-65-1' OR E.ELRG_NAME = 'n-propylbenzene' THEN E.ELRG_RTXT END) AS "Propylbenzene ",
    
    -- (110) Styrene
    MAX(CASE WHEN E.ELRG_CODE = '100-42-5' OR E.ELRG_NAME = 'Styrene' THEN E.ELRG_RTXT END) AS "Styrene  ",

-- STREAMING_CHUNK: Pivoting ELRG Chlorobenzenes...
    -- 15. Pivoted Chlorobenzenes
    
    -- (111) Chlorobenzene
    MAX(CASE WHEN E.ELRG_CODE = '108-90-7' OR E.ELRG_NAME = 'Chlorobenzene' THEN E.ELRG_RTXT END) AS "Chlorobenzene",
    
    -- (112) 1,2-dichlorobenzene (1,2-DCB)
    MAX(CASE WHEN E.ELRG_CODE = '95-50-1' OR E.ELRG_NAME = '1,2-Dichlorobenzene' THEN E.ELRG_RTXT END) AS "1,2-dichlorobenzene (1,2-DCB) ",
    
    -- (113) 1,3-dichlorobenzene (1,3-DCB)
    MAX(CASE WHEN E.ELRG_CODE = '541-73-1' OR E.ELRG_NAME = '1,3-Dichlorobenzene' THEN E.ELRG_RTXT END) AS "1,3-dichlorobenzene (1,3-DCB) ",
    
    -- (114) 1-4-dichlorobenzene (1,4-DCB)
    MAX(CASE WHEN E.ELRG_CODE = '106-46-7' OR E.ELRG_NAME = '1,4-Dichlorobenzene' THEN E.ELRG_RTXT END) AS "1-4-dichlorobenzene (1,4-DCB) ",
    
    -- (115) 1,2,3-Trichlorobenzene
    MAX(CASE WHEN E.ELRG_CODE = '87-61-6' OR E.ELRG_NAME = '1,2,3-trichlorobenzene' THEN E.ELRG_RTXT END) AS "1,2,3-Trichlorobenzene ",
    
    -- (116) 1,2,4- Trichlorobenzene
    MAX(CASE WHEN E.ELRG_CODE = '120-82-1' OR E.ELRG_NAME = '1,2,4-Trichlorobenzene' THEN E.ELRG_RTXT END) AS "1,2,4- Trichlorobenzene ",
    
    -- (117) 1,3,5- Trichlorobenzene
    MAX(CASE WHEN E.ELRG_CODE = '108-70-3' OR E.ELRG_NAME = '1,3,5-Trichlorobenzene' THEN E.ELRG_RTXT END) AS "1,3,5- Trichlorobenzene ",
    
    -- (118) 1,2,3,4-Tetrachlorobenzene
    MAX(CASE WHEN E.ELRG_CODE = '634-66-2' OR E.ELRG_NAME = '1,2,3,4-tetrachlorobenzene' THEN E.ELRG_RTXT END) AS "1,2,3,4-Tetrachlorobenzene ",
    
    -- (119) 1,2,3,5- Tetrachlorobenzene
    MAX(CASE WHEN E.ELRG_CODE = '634-90-2' OR E.ELRG_NAME = '1,2,3,5-tetrachlorobenzene' THEN E.ELRG_RTXT END) AS "1,2,3,5- Tetrachlorobenzene ",
    
    -- (120) 1,2,4,5- Tetrachlorobenzene
    MAX(CASE WHEN E.ELRG_CODE = '95-94-3' OR E.ELRG_NAME = '1,2,4,5-tetrachlorobenzene' THEN E.ELRG_RTXT END) AS "1,2,4,5- Tetrachlorobenzene ",
    
    -- (121) Pentachlorobenzene (PECB)
    MAX(CASE WHEN E.ELRG_CODE = '608-93-5' OR E.ELRG_NAME = 'pentachlorobenzene' THEN E.ELRG_RTXT END) AS "Pentachlorobenzene (PECB) ",
    
    -- (122) Hexachlorobenzene (HCB)
    MAX(CASE WHEN E.ELRG_CODE = '118-74-1' OR E.ELRG_NAME = 'Hexachlorobenzene' THEN E.ELRG_RTXT END) AS "Hexachlorobenzene (HCB) ",

-- STREAMING_CHUNK: Correlating spatial parameters and completing join...
    -- 16. Geometry mapping column for QGIS SpatiaLite / GeoPackage Engine
    L.geom

FROM 
    ELRG E

-- Join back to the exploratory hole location spatial table to pull coordinates and ground level
LEFT JOIN 
    loca L ON E.LOCA_ID = L.LOCA_ID

WHERE
    -- Exclude liquid/aqueous units (mg/l, ug/l) to ensure we only process soil/solid data.
    E.ELRG_RUNI NOT IN ('mg/l', 'ug/l')

GROUP BY 
    E.LOCA_ID, 
    E.SAMP_TOP, 
    E.SAMP_TYPE, 
    E.SAMP_REF,
    L.geom,
    L.LOCA_NATE,
    L.LOCA_NATN,
    L.LOCA_GL
ORDER BY 
    E.LOCA_ID ASC, 
    CAST(E.SAMP_TOP AS REAL) ASC;