-- ==============================================================================
-- QUERY TITLE       : QGIS Dynamic Borehole Log Label Generator
-- AUTHOR / EMAIL    : Richard Meredith / richard.meredith@geo-env.co.uk
-- ORGANIZATION      : GeoEnvironmental Consulting Ltd
-- PROJECT / TOOLS   : AGS Tools Project (FOSS)
-- LICENSE           : GNU GPL v3 (GPL-compatible open-source)
-- COMPATIBILITY     : QGIS 3.x (SpatiaLite / GeoPackage SQLite Provider)
-- AGS VERSION       : AGS 4.0.x / 4.1.x
-- SOURCE TABLES     : GEOL, LOCA
-- DESCRIPTION       : Concatenates and formats borehole location details, depth-sequenced stratigraphy intervals (truncated to 500 characters), and final termination depths with elevations (mAOD) into a piped multi-line string for dynamic QGIS map labels.
-- ==============================================================================

-- ==============================================================================
-- ⚖️ GNU GPL v3 LICENSE & PROFESSIONAL DISCLAIMER 
-- ==============================================================================
-- Copyright (C) 2026 GeoEnvironmental Consulting Ltd
--
-- This SQL query is free software: you can redistribute it and/or modify
-- it under the terms of the GNU General Public License as published by
-- the Free Software Foundation, version 3 of the License.
--
-- This code is distributed WITHOUT ANY WARRANTY; without even the implied 
-- warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
-- GNU General Public License for more details <https://www.gnu.org/licenses/>.
--
-- TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW:
-- 1. All implied terms, conditions, and warranties—including but not limited to 
--    implied terms of SATISFACTORY QUALITY, FITNESS FOR A PARTICULAR PURPOSE, 
--    and non-infringement of intellectual property—are hereby EXCLUDED.
--
-- 2. The author and GeoEnvironmental Consulting Ltd shall not be liable for any 
--    direct, indirect, incidental, or consequential loss or damage (including 
--    but not limited to site engineering errors, financial loss, business 
--    disruption, or data corruption) arising from the use of, or reliance upon, 
--    the outputs generated by this script.
--
-- 3. PROFESSIONAL RESPONSIBILITY (THE 'ENGAGE BRAIN' DIRECTIVE): 
--    This SQL query is a spatial processing tool, not a crystal ball. 
--    It does not replace professional, qualified human interpretation. Users are 
--    respectfully but firmly reminded to engage their brains (specifically ensuring 
--    cognition is in a forward gear) before executing this script or trusting its 
--    outputs. Trusting automated spatial interpolation blindly is a guaranteed 
--    recipe for causing expensive mistakes.
--
-- NOTHING IN THIS DISCLAIMER SHALL LIMIT OR EXCLUDE LIABILITY FOR:
-- (a) Death or personal injury resulting from negligence;
-- (b) Fraud or fraudulent misrepresentation; or
-- (c) Any other liability which cannot be excluded or limited under the laws of 
--     England and Wales.
-- ==============================================================================

SELECT 
    L.geom, -- Select the spatial geometry data.
    L."LOCA_ID", -- Select the location ID.
    
    -- 1. HEADER LINE: "Borehole ID (GL: XX.XXmAOD)"
    L."LOCA_ID" || 
    CASE 
        WHEN L."LOCA_GL" IS NOT NULL AND L."LOCA_GL" != '' 
        THEN ' (GL: ' || L."LOCA_GL" || 'mAOD)' 
        ELSE '' 
    END || '|' ||
    
    -- 2. GEOLOGY LINES: Stacking the sorted, truncated stratigraphy layers
    GROUP_CONCAT(
        '[' || inner_query."From (m)" || 'm - ' || inner_query."To (m)" || 'm] ' || 
        inner_query."Stratum Description", 
        '|' 
    ) || '|' || -- Pipe at the end drops us down to the footer line
    
    -- 3. FOOTER LINE: "Borehole ID; End of Hole: XX.XXm / XX.XXmAOD"
    L."LOCA_ID" || '; End of Hole: ' || 
    CASE 
        -- FIXED: Used L."LOCA_FDEP" consistently throughout the calculation
        WHEN L."LOCA_GL" IS NOT NULL AND L."LOCA_GL" != '' AND L."LOCA_FDEP" IS NOT NULL AND L."LOCA_FDEP" != ''
        THEN L."LOCA_FDEP" || 'm depth (' || PRINTF('%.2f', CAST(L."LOCA_GL" AS FLOAT) - CAST(L."LOCA_FDEP" AS FLOAT)) || 'mAOD)'
        
        -- Situation B: We only have Final Depth -> Just show the depth
        WHEN L."LOCA_FDEP" IS NOT NULL AND L."LOCA_FDEP" != ''
        THEN L."LOCA_FDEP" || 'm depth'
        
        -- Situation C: Data is missing
        ELSE 'Depth Unknown'
    END AS "descriptions"

FROM 
    LOCA L -- Main location table

-- Join with the subquery that retrieves and sorts geological information
JOIN 
    (
        SELECT 
            "LOCA_ID", 
            CAST("GEOL_TOP" AS NUMERIC) AS "From (m)", 
            "GEOL_BASE" AS "To (m)", 
            SUBSTR("GEOL_DESC", 1, 500) AS "Stratum Description" 
        FROM 
            "GEOL" 
        ORDER BY 
            "LOCA_ID", 
            CAST("GEOL_TOP" AS NUMERIC) 
    ) AS inner_query 

ON L."LOCA_ID" = inner_query."LOCA_ID"

GROUP BY 
    L."LOCA_ID";
