-- ==============================================================================
-- QUERY TITLE       : Tabulates Standard Penetration Test (SPT) Summary
-- AUTHOR / ORG      : Richard Meredith / GeoEnvironmental Consulting Ltd
-- PROJECT / TOOLS   : AGS Tools Project (FOSS)
-- LICENSE           : MIT / Creative Commons CC0 (FOSS-friendly)
-- DIALECT           : SQLite / GeoPackage (Optimized for QGIS)
-- SOURCE TABLES     : ISPT, LOCA, GEOL
-- DESCRIPTION       :
--   Extracts Standard Penetration Test details from the ISPT group, pairs them
--   with geographic coordinate attributes from LOCA, and correlates the test depth
--   back to the geological logging table (GEOL) to pull relevant stratum 
--   descriptions and legend codes.
--
--   SPATIALLY ENABLED: Retains Easting, Northing, and computes elevations in mAOD
--   relative to Ground Level (Z = LOCA_GL - Test Depth).
--
--   TABLE GENERATION AIM:
--   Structured specifically to enable clean data visualization, statistical analysis,
--   and generating plots (such as SPT N-value profiles vs. Depth or Elevation)
--   using external tools like Excel, Python (Matplotlib/Seaborn), or directly inside QGIS
--   using plugins like DataPlotly.
-- ==============================================================================
-- ⚖️ GNU GPL v3 LICENSE & PROFESSIONAL DISCLAIMER 
-- ==============================================================================
-- Copyright (C) 2026 GeoEnvironmental Consulting Ltd
--
-- This SQL query is free software: you can redistribute it and/or modify
-- it under the terms of the GNU General Public License as published by
-- the Free Software Foundation, version 3 of the License.
--
-- This code is distributed WITHOUT ANY WARRANTY; without even the implied 
-- warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
-- GNU General Public License for more details <https://www.gnu.org/licenses/>.
--
-- TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW:
-- 1. All implied terms, conditions, and warranties—including but not limited to 
--    implied terms of SATISFACTORY QUALITY, FITNESS FOR A PARTICULAR PURPOSE, 
--    and non-infringement of intellectual property—are hereby EXCLUDED.
--
-- 2. The author and GeoEnvironmental Consulting Ltd shall not be liable for any 
--    direct, indirect, incidental, or consequential loss or damage (including 
--    but not limited to site engineering errors, financial loss, business 
--    disruption, or data corruption) arising from the use of, or reliance upon, 
--    the outputs generated by this script.
--
-- 3. PROFESSIONAL RESPONSIBILITY (THE 'ENGAGE BRAIN' DIRECTIVE): 
--    This SQL query is a spatial processing tool, not a crystal ball. 
--    It does not replace professional, qualified human interpretation. Users are 
--    respectfully but firmly reminded to engage their brains (specifically ensuring 
--    cognition is in a forward gear) before executing this script or trusting its 
--    outputs. Trusting automated spatial interpolation blindly is a guaranteed 
--    recipe for causing expensive mistakes.
--
-- NOTHING IN THIS DISCLAIMER SHALL LIMIT OR EXCLUDE LIABILITY FOR:
-- (a) Death or personal injury resulting from negligence;
-- (b) Fraud or fraudulent misrepresentation; or
-- (c) Any other liability which cannot be excluded or limited under the laws of 
--     England and Wales.
-- ==============================================================================


SELECT 
    -- 1. QGIS Unique Feature Identifier
    ROW_NUMBER() OVER () AS fid,

    -- 2. Location & Spatial Identifiers
    I.LOCA_ID AS "Exploratory Hole Location",
    CAST(NULLIF(L.LOCA_NATE, '') AS REAL) AS "Easting",
    CAST(NULLIF(L.LOCA_NATN, '') AS REAL) AS "Northing",
    CAST(NULLIF(L.LOCA_GL, '') AS REAL) AS "Ground Level (mAOD)",
    
    -- 3. Dynamic Geology Legend Lookup
    -- Pulls the legend code from GEOL_LEG at the exact depth of the test
    (
        SELECT G.GEOL_LEG 
        FROM GEOL G 
        WHERE G.LOCA_ID = I.LOCA_ID 
          AND CAST(NULLIF(I.ISPT_TOP, '') AS REAL) >= CAST(NULLIF(G.GEOL_TOP, '') AS REAL)
          AND CAST(NULLIF(I.ISPT_TOP, '') AS REAL) <= CAST(NULLIF(G.GEOL_BASE, '') AS REAL)
        ORDER BY CAST(NULLIF(G.GEOL_TOP, '') AS REAL) ASC 
        LIMIT 1
    ) AS "Geology Legend Code (GEOL_LEG)",

    -- 4. Depth & Calculated Test Levels
    CAST(NULLIF(I.ISPT_TOP, '') AS REAL) AS "Test Depth (m)",
    
    -- Level calculation: Z = Ground Level - Test Depth
    ROUND(
        CAST(NULLIF(L.LOCA_GL, '') AS REAL) - 
        CAST(NULLIF(I.ISPT_TOP, '') AS REAL), 
        2
    ) AS "Test Level (mAOD)",

    -- 5. Dynamic Geological Description Lookup
    -- Uses a subquery with LIMIT 1 to prevent row multiplication in case of overlapping GEOL boundaries
    (
        SELECT G.GEOL_DESC 
        FROM GEOL G 
        WHERE G.LOCA_ID = I.LOCA_ID 
          AND CAST(NULLIF(I.ISPT_TOP, '') AS REAL) >= CAST(NULLIF(G.GEOL_TOP, '') AS REAL)
          AND CAST(NULLIF(I.ISPT_TOP, '') AS REAL) <= CAST(NULLIF(G.GEOL_BASE, '') AS REAL)
        ORDER BY CAST(NULLIF(G.GEOL_TOP, '') AS REAL) ASC 
        LIMIT 1
    ) AS "Sample Geology Description",

    -- 6. Core SPT Test Specifics (Strictly Mapped to AGS 4 Guidelines)
    I.ISPT_TYPE AS "Test Type (S/C)",
    I.ISPT_METH AS "Test Standard / Method",

    -- 7. N-Value Outputs (Dual Formats for Auditing and Plotting)
    I.ISPT_REP AS "Reported SPT N-Value (Raw)",
    
    -- Cleaned Numeric N-Value for Plotting:
    -- References the Main Test Drive blow count (ISPT_MAIN) in numerical form,
    -- removing any potential non-numeric characters to allow SQLite to parse it
    -- as a numeric float for direct charting and thematic styling in QGIS.
    CAST(
        NULLIF(
            TRIM(
                REPLACE(
                    REPLACE(
                        REPLACE(
                            REPLACE(
                                REPLACE(I.ISPT_MAIN, '>', ''), 
                                '<', ''
                            ), 
                            '+', ''
                        ), 
                        'Refusal', ''
                    ), 
                    'Ref', ''
                )
            ), 
            ''
        ) AS REAL
    ) AS "Numeric N-Value (for Plotting)",

    -- 8. Seating and Main Blow Totals
    CAST(NULLIF(I.ISPT_SEAT, '') AS REAL) AS "Seating Blow Count",
    CAST(NULLIF(I.ISPT_MAIN, '') AS REAL) AS "Main Blow Count",

    -- 9. Increment Blow Counts (Six increments of 75mm: 1 & 2 are Seating, 3-6 are Main Test)
    CAST(NULLIF(I.ISPT_INC1, '') AS REAL) AS "Blows - Seating 1 (0-75mm)",
    CAST(NULLIF(I.ISPT_INC2, '') AS REAL) AS "Blows - Seating 2 (75-150mm)",
    CAST(NULLIF(I.ISPT_INC3, '') AS REAL) AS "Blows - Main 1 (150-225mm)",
    CAST(NULLIF(I.ISPT_INC4, '') AS REAL) AS "Blows - Main 2 (225-300mm)",
    CAST(NULLIF(I.ISPT_INC5, '') AS REAL) AS "Blows - Main 3 (300-375mm)",
    CAST(NULLIF(I.ISPT_INC6, '') AS REAL) AS "Blows - Main 4 (375-450mm)",

    -- 10. Increment Penetrations (Standard target is 75mm per increment)
    CAST(NULLIF(I.ISPT_PEN1, '') AS REAL) AS "Penetration (mm) - Seating 1",
    CAST(NULLIF(I.ISPT_PEN2, '') AS REAL) AS "Penetration (mm) - Seating 2",
    CAST(NULLIF(I.ISPT_PEN3, '') AS REAL) AS "Penetration (mm) - Main 1",
    CAST(NULLIF(I.ISPT_PEN4, '') AS REAL) AS "Penetration (mm) - Main 2",
    CAST(NULLIF(I.ISPT_PEN5, '') AS REAL) AS "Penetration (mm) - Main 3",
    CAST(NULLIF(I.ISPT_PEN6, '') AS REAL) AS "Penetration (mm) - Main 4",

    -- 11. Equipment Parameters, Environmental Metadata & Remarks
    I.ISPT_HAM AS "SPT Hammer Reference",
    CAST(NULLIF(I.ISPT_ERAT, '') AS REAL) AS "Hammer Energy Ratio (%)",
    CAST(NULLIF(I.ISPT_CAS, '') AS REAL) AS "Casing Depth (m)",
    CAST(NULLIF(I.ISPT_WAT, '') AS REAL) AS "Borehole Water Depth (m)",
    I.ISPT_REM AS "Test Remarks",
    
    -- 12. Spatial Geometry Column for plotting directly as a Spatial Layer in QGIS
    L.geom

FROM 
    ISPT I

-- Spatial join with Location parameters
LEFT JOIN 
    loca L ON I.LOCA_ID = L.LOCA_ID

ORDER BY 
    I.LOCA_ID ASC, 
    "Test Depth (m)" ASC;
