-- ==============================================================================
-- QUERY TITLE       : Tabulates In Situ Vane Test Summary using IVAN group
-- AUTHOR / ORG      : Richard Meredith / GeoEnvironmental Consulting Ltd
-- PROJECT / TOOLS   : AGS Tools Project (FOSS)
-- LICENSE           : MIT / Creative Commons CC0 (FOSS-friendly)
-- DIALECT           : SQLite / GeoPackage (Optimized for QGIS)
-- SOURCE TABLES     : IVAN, LOCA, GEOL
-- DESCRIPTION       :
--   Extracts In Situ Vane test details from the IVAN group, pairs them 
--   with geographic coordinate attributes from LOCA, and correlates the test depth
--   back to the geological logging table (GEOL) to pull relevant stratum 
--   descriptions and legend codes.
--
--   SPATIALLY ENABLED: Retains Easting, Northing, and computes elevations in mAOD
--   relative to Ground Level (Z = LOCA_GL - Test Depth).
--
--   TABLE GENERATION AIM:
--   Structured specifically to enable clean data visualization, statistical analysis,
--   and generating plots (such as Peak and Remoulded Shear Strength vs. Depth or Elevation,
--   or Sensitivity profiles) using external tools like Excel, Python (Matplotlib/Seaborn),
--   or directly inside QGIS using plugins like DataPlotly.
-- ==============================================================================
-- ⚖️ GNU GPL v3 LICENSE & PROFESSIONAL DISCLAIMER 
-- ==============================================================================
-- Copyright (C) 2026 GeoEnvironmental Consulting Ltd
--
-- This SQL query is free software: you can redistribute it and/or modify
-- it under the terms of the GNU General Public License as published by
-- the Free Software Foundation, version 3 of the License.
--
-- This code is distributed WITHOUT ANY WARRANTY; without even the implied 
-- warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
-- GNU General Public License for more details <https://www.gnu.org/licenses/>.
--
-- TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW:
-- 1. All implied terms, conditions, and warranties—including but not limited to 
--    implied terms of SATISFACTORY QUALITY, FITNESS FOR A PARTICULAR PURPOSE, 
--    and non-infringement of intellectual property—are hereby EXCLUDED.
--
-- 2. The author and GeoEnvironmental Consulting Ltd shall not be liable for any 
--    direct, indirect, incidental, or consequential loss or damage (including 
--    but not limited to site engineering errors, financial loss, business 
--    disruption, or data corruption) arising from the use of, or reliance upon, 
--    the outputs generated by this script.
--
-- 3. PROFESSIONAL RESPONSIBILITY (THE 'ENGAGE BRAIN' DIRECTIVE): 
--    This SQL query is a spatial processing tool, not a crystal ball. 
--    It does not replace professional, qualified human interpretation. Users are 
--    respectfully but firmly reminded to engage their brains (specifically ensuring 
--    cognition is in a forward gear) before executing this script or trusting its 
--    outputs. Trusting automated spatial interpolation blindly is a guaranteed 
--    recipe for causing expensive mistakes.
--
-- NOTHING IN THIS DISCLAIMER SHALL LIMIT OR EXCLUDE LIABILITY FOR:
-- (a) Death or personal injury resulting from negligence;
-- (b) Fraud or fraudulent misrepresentation; or
-- (c) Any other liability which cannot be excluded or limited under the laws of 
--     England and Wales.
-- ==============================================================================


SELECT 
    -- 1. QGIS Unique Feature Identifier
    ROW_NUMBER() OVER () AS fid,

    -- 2. Location & Spatial Identifiers
    I.LOCA_ID AS "Exploratory Hole Location",
    CAST(NULLIF(L.LOCA_NATE, '') AS REAL) AS "Easting",
    CAST(NULLIF(L.LOCA_NATN, '') AS REAL) AS "Northing",
    CAST(NULLIF(L.LOCA_GL, '') AS REAL) AS "Ground Level (mAOD)",
    
    -- 3. Dynamic Geology Legend Lookup
    -- Pulls the legend code from GEOL_LEG at the exact depth of the test
    (
        SELECT G.GEOL_LEG 
        FROM GEOL G 
        WHERE G.LOCA_ID = I.LOCA_ID 
          AND CAST(NULLIF(I.IVAN_DPTH, '') AS REAL) >= CAST(NULLIF(G.GEOL_TOP, '') AS REAL)
          AND CAST(NULLIF(I.IVAN_DPTH, '') AS REAL) <= CAST(NULLIF(G.GEOL_BASE, '') AS REAL)
        ORDER BY CAST(NULLIF(G.GEOL_TOP, '') AS REAL) ASC 
        LIMIT 1
    ) AS "Geology Legend Code (GEOL_LEG)",

    -- 4. Depth & Calculated Test Levels
    CAST(NULLIF(I.IVAN_DPTH, '') AS REAL) AS "Test Depth (m)",
    
    -- Level calculation: Z = Ground Level - Test Depth
    ROUND(
        CAST(NULLIF(L.LOCA_GL, '') AS REAL) - 
        CAST(NULLIF(I.IVAN_DPTH, '') AS REAL), 
        2
    ) AS "Test Level (mAOD)",

    -- 5. Dynamic Geological Description Lookup
    -- Uses a subquery with LIMIT 1 to prevent row multiplication in case of overlapping GEOL boundaries
    (
        SELECT G.GEOL_DESC 
        FROM GEOL G 
        WHERE G.LOCA_ID = I.LOCA_ID 
          AND CAST(NULLIF(I.IVAN_DPTH, '') AS REAL) >= CAST(NULLIF(G.GEOL_TOP, '') AS REAL)
          AND CAST(NULLIF(I.IVAN_DPTH, '') AS REAL) <= CAST(NULLIF(G.GEOL_BASE, '') AS REAL)
        ORDER BY CAST(NULLIF(G.GEOL_TOP, '') AS REAL) ASC 
        LIMIT 1
    ) AS "Sample Geology Description",

    -- 6. Core Vane Test Specifics (AGS 4 Guidelines)
    I.IVAN_TESN AS "Test Reference",
    I.IVAN_METH AS "Test Standard / Method",
    I.IVAN_TYPE AS "Vane Type",

    -- 7. Core Geotechnical Test Results
    -- Casts results to preserve numeric compatibility for thematic mapping and plotting
    CAST(NULLIF(I.IVAN_IVAN, '') AS REAL) AS "Peak Undrained Shear Strength (kPa)",
    CAST(NULLIF(I.IVAN_IVAR, '') AS REAL) AS "Remoulded Undrained Shear Strength (kPa)",
    
    -- Dynamic Sensitivity Calculation (Peak / Remoulded)
    -- Safely checks for nulls and prevents division-by-zero errors in SQLite
    CASE 
        WHEN CAST(NULLIF(I.IVAN_IVAR, '') AS REAL) > 0 
        THEN ROUND(CAST(NULLIF(I.IVAN_IVAN, '') AS REAL) / CAST(NULLIF(I.IVAN_IVAR, '') AS REAL), 2)
        ELSE NULL 
    END AS "Sensitivity (Calculated)",

    -- 8. Remarks & Environmental Geometry
    I.IVAN_REM AS "Test Remarks",
    L.geom

FROM 
    IVAN I

-- Spatial join with Location parameters
LEFT JOIN 
    loca L ON I.LOCA_ID = L.LOCA_ID

ORDER BY 
    I.LOCA_ID ASC, 
    "Test Depth (m)" ASC,
    I.IVAN_TESN ASC;
