-- ==============================================================================
-- QUERY TITLE       : Tabulates Triaxial Strength Test Summary using TRIT group
-- AUTHOR / ORG      : Richard Meredith / GeoEnvironmental Consulting Ltd
-- PROJECT / TOOLS   : AGS Tools Project (FOSS)
-- LICENSE           : MIT / Creative Commons CC0 (FOSS-friendly)
-- DIALECT           : SQLite / GeoPackage (Optimized for QGIS)
-- SOURCE TABLES     : TRIT, LOCA, GEOL
-- DESCRIPTION       :
--   Extracts total stress triaxial test details from the TRIT group and pairs them 
--   with geographic coordinate attributes from LOCA, and correlates the specimen 
--   depth back to the geological logging table (GEOL) to pull relevant stratum 
--   descriptions and legend codes.
--
--   SPATIALLY ENABLED: Retains Easting, Northing, and computes elevations in mAOD
--   relative to Ground Level (Z = LOCA_GL - Specimen Depth).
--
--   TABLE GENERATION AIM:
--   Structured specifically to enable clean data visualization and  
--   generating plots (such as Undrained Shear Strength (Cu) vs. Depth or Elevation) 
--   using external tools like Excel, Python (Matplotlib/Seaborn), or directly inside QGIS 
--   using plugins like DataPlotly.
-- ==============================================================================
-- ⚖️ GNU GPL v3 LICENSE & PROFESSIONAL DISCLAIMER 
-- ==============================================================================
-- Copyright (C) 2026 GeoEnvironmental Consulting Ltd
--
-- This SQL query is free software: you can redistribute it and/or modify
-- it under the terms of the GNU General Public License as published by
-- the Free Software Foundation, version 3 of the License.
--
-- This code is distributed WITHOUT ANY WARRANTY; without even the implied 
-- warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
-- GNU General Public License for more details <https://www.gnu.org/licenses/>.
--
-- TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW:
-- 1. All implied terms, conditions, and warranties—including but not limited to 
--    implied terms of SATISFACTORY QUALITY, FITNESS FOR A PARTICULAR PURPOSE, 
--    and non-infringement of intellectual property—are hereby EXCLUDED.
--
-- 2. The author and GeoEnvironmental Consulting Ltd shall not be liable for any 
--    direct, indirect, incidental, or consequential loss or damage (including 
--    but not limited to site engineering errors, financial loss, business 
--    disruption, or data corruption) arising from the use of, or reliance upon, 
--    the outputs generated by this script.
--
-- 3. PROFESSIONAL RESPONSIBILITY (THE 'ENGAGE BRAIN' DIRECTIVE): 
--    This SQL query is a spatial processing tool, not a crystal ball. 
--    It does not replace professional, qualified human interpretation. Users are 
--    respectfully but firmly reminded to engage their brains (specifically ensuring 
--    cognition is in a forward gear) before executing this script or trusting its 
--    outputs. Trusting automated spatial interpolation blindly is a guaranteed 
--    recipe for causing expensive mistakes.
--
-- NOTHING IN THIS DISCLAIMER SHALL LIMIT OR EXCLUDE LIABILITY FOR:
-- (a) Death or personal injury resulting from negligence;
-- (b) Fraud or fraudulent misrepresentation; or
-- (c) Any other liability which cannot be excluded or limited under the laws of 
--     England and Wales.
-- ==============================================================================


SELECT 
    -- 1. QGIS Unique Feature Identifier
    ROW_NUMBER() OVER () AS fid,

    -- 2. Location & Spatial Identifiers
    T.LOCA_ID AS "Exploratory Hole Location",
-- STREAMING_CHUNK: Mapping National Grid coordinate fields...
    CAST(NULLIF(L.LOCA_NATE, '') AS REAL) AS "Easting",
    CAST(NULLIF(L.LOCA_NATN, '') AS REAL) AS "Northing",
    CAST(NULLIF(L.LOCA_GL, '') AS REAL) AS "Ground Level (mAOD)",
    
    -- 3. Specimen Specifics & Sample Metadata
    T.SAMP_REF AS "Sample Reference",
    T.SAMP_TYPE AS "Sample Type",
    CAST(NULLIF(T.SAMP_TOP, '') AS REAL) AS "Sample top depth",
    T.SPEC_REF AS "Specimen Reference",
    
-- STREAMING_CHUNK: Executing depth-matched geological legend lookup...
    -- Dynamic Geology Legend Code lookup at specimen depth (from GEOL_LEG)
    (
        SELECT G.GEOL_LEG 
        FROM GEOL G 
        WHERE G.LOCA_ID = T.LOCA_ID 
          AND CAST(NULLIF(COALESCE(T.SPEC_DPTH, T.SAMP_TOP), '') AS REAL) >= CAST(NULLIF(G.GEOL_TOP, '') AS REAL)
          AND CAST(NULLIF(COALESCE(T.SPEC_DPTH, T.SAMP_TOP), '') AS REAL) <= CAST(NULLIF(G.GEOL_BASE, '') AS REAL)
        ORDER BY CAST(NULLIF(G.GEOL_TOP, '') AS REAL) ASC 
        LIMIT 1
    ) AS "Geology Legend Code (GEOL_LEG)",
    
    -- 4. Depth & Calculated Specimen Levels
    -- Prioritises SPEC_DPTH (specimen-specific depth) and falls back to SAMP_TOP
    CAST(NULLIF(COALESCE(T.SPEC_DPTH, T.SAMP_TOP), '') AS REAL) AS "Specimen Depth (m)",
    
    -- Level calculation: Z = Ground Level - Specimen Depth
    ROUND(
        CAST(NULLIF(L.LOCA_GL, '') AS REAL) - 
        CAST(NULLIF(COALESCE(T.SPEC_DPTH, T.SAMP_TOP), '') AS REAL), 
        2
    ) AS "Specimen Level (mAOD)",

-- STREAMING_CHUNK: Correlating specimen depth with geological unit descriptions...
    -- 5. Dynamic Geological Description lookup at specimen depth
    -- Uses a subquery with LIMIT 1 to prevent row multiplication in case of overlapping GEOL boundaries
    (
        SELECT G.GEOL_DESC 
        FROM GEOL G 
        WHERE G.LOCA_ID = T.LOCA_ID 
          AND CAST(NULLIF(COALESCE(T.SPEC_DPTH, T.SAMP_TOP), '') AS REAL) >= CAST(NULLIF(G.GEOL_TOP, '') AS REAL)
          AND CAST(NULLIF(COALESCE(T.SPEC_DPTH, T.SAMP_TOP), '') AS REAL) <= CAST(NULLIF(G.GEOL_BASE, '') AS REAL)
        ORDER BY CAST(NULLIF(G.GEOL_TOP, '') AS REAL) ASC 
        LIMIT 1
    ) AS "Sample Geology Description",

    -- 6. Core Geotechnical Test Results
    -- Casts results to preserve numeric compatibility for thematic mapping and statistics
    CAST(NULLIF(T.TRIT_CU, '') AS REAL) AS "Undrained Shear Strength at Failure (kPa)",
    CAST(NULLIF(T.TRIT_BDEN, '') AS REAL) AS "Initial Bulk Density (Mg/m3)",
    CAST(NULLIF(T.TRIT_DDEN, '') AS REAL) AS "Initial Dry Density (Mg/m3)",
    CAST(NULLIF(T.TRIT_CELL, '') AS REAL) AS "Cell Pressure (kPa)",
    CAST(NULLIF(T.TRIT_DEVF, '') AS REAL) AS "Deviator Stress at Failure (kPa)",
    CAST(NULLIF(T.TRIT_STRN, '') AS REAL) AS "Axial Strain at Failure (%)",
    
    -- Include comments and geometry
    T.TRIT_REM AS "Test Remarks",
    L.geom

FROM 
    TRIT T

-- Join location parameters to calculate levels and fetch coordinates
LEFT JOIN 
    loca L ON T.LOCA_ID = L.LOCA_ID

ORDER BY 
    T.LOCA_ID ASC, 
    "Specimen Depth (m)" ASC, 
    T.SPEC_REF ASC, 
    T.TRIT_TESN ASC;
