-- ==============================================================================
-- QUERY TITLE       : GEOL and DETL Contamination and Odour Search (Spatially Enabled)
-- AUTHOR / EMAIL    : Richard Meredith / richard.meredith@geo-env.co.uk
-- ORGANIZATION      : GeoEnvironmental Consulting Ltd
-- PROJECT / TOOLS   : AGS Tools Project (FOSS)
-- LICENSE           : GNU GPL v3 (GPL-compatible open-source)
-- COMPATIBILITY     : QGIS 3.x (SpatiaLite / GeoPackage SQLite Provider)
-- AGS VERSION       : AGS 4.0.x / 4.1.x
-- SOURCE TABLES     : GEOL / DETL / LOCA
-- DESCRIPTION       : Scans both geological layer descriptions (GEOL) and detailed remarks (DETL) for visual, chemical, physical, and olfactory contamination indicators (such as odour, smell, sheen, hydrocarbons, staining, and asbestos). Joins the unified results with LOCA to populate coordinates, ground elevations, and dynamic reduced levels.
-- ==============================================================================

-- ==============================================================================
-- ⚖️ GNU GPL v3 LICENSE & PROFESSIONAL DISCLAIMER 
-- ==============================================================================
-- Copyright (C) 2026 GeoEnvironmental Consulting Ltd
--
-- This SQL query is free software: you can redistribute it and/or modify
-- it under the terms of the GNU General Public License as published by
-- the Free Software Foundation, version 3 of the License.
--
-- This code is distributed WITHOUT ANY WARRANTY; without even the implied 
-- warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
-- GNU General Public License for more details <https://www.gnu.org/licenses/>.
--
-- TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW:
-- 1. All implied terms, conditions, and warranties—including but not limited to 
--    implied terms of SATISFACTORY QUALITY, FITNESS FOR A PARTICULAR PURPOSE, 
--    and non-infringement of intellectual property—are hereby EXCLUDED.
--
-- 2. The author and GeoEnvironmental Consulting Ltd shall not be liable for any 
--    direct, indirect, incidental, or consequential loss or damage (including 
--    but not limited to site engineering errors, financial loss, business 
--    disruption, or data corruption) arising from the use of, or reliance upon, 
--    the outputs generated by this script.
--
-- 3. PROFESSIONAL RESPONSIBILITY (THE 'ENGAGE BRAIN' DIRECTIVE): 
--    This SQL query is a spatial processing tool, not a crystal ball. 
--    It does not replace professional, qualified human interpretation. Users are 
--    respectfully but firmly reminded to engage their brains (specifically ensuring 
--    cognition is in a forward gear) before executing this script or trusting its 
--    outputs. Trusting automated spatial interpolation blindly is a guaranteed 
--    recipe for causing expensive mistakes.
--
-- NOTHING IN THIS DISCLAIMER SHALL LIMIT OR EXCLUDE LIABILITY FOR:
-- (a) Death or personal injury resulting from negligence;
-- (b) Fraud or fraudulent misrepresentation; or
-- (c) Any other liability which cannot be excluded or limited under the laws of 
--     England and Wales.
-- ==============================================================================

WITH UnifiedContam AS (
    -- 1. Extract records matching keywords from the main geological description table (GEOL)
    SELECT
        'GEOL' AS "Source Table",
        G.loca_id,
        CAST(NULLIF(G.geol_top, '') AS REAL) AS top_m,
        CAST(NULLIF(G.geol_base, '') AS REAL) AS base_m,
        G.geol_desc AS description,
        NULL AS remarks -- GEOL does not contain a secondary remarks column
    FROM GEOL G
    WHERE
        G.geol_desc LIKE '%odour%' OR
        G.geol_desc LIKE '%contam%' OR
        G.geol_desc LIKE '%stain%' OR
        G.geol_desc LIKE '%smell%' OR
        G.geol_desc LIKE '%sheen%' OR
        G.geol_desc LIKE '% oil%' OR
        G.geol_desc LIKE '%hydrocarbon%' OR
        G.geol_desc LIKE '%chemical%' OR
        G.geol_desc LIKE '%asbestos%'

    UNION ALL

    -- 2. Extract records matching keywords from the detailed remarks/description table (DETL)
    SELECT
        'DETL' AS "Source Table",
        D.loca_id,
        CAST(NULLIF(D.detl_top, '') AS REAL) AS top_m,
        CAST(NULLIF(D.detl_base, '') AS REAL) AS base_m,
        D.detl_desc AS description,
        D.detl_rem AS remarks
    FROM DETL D
    WHERE
        D.detl_rem LIKE '%odour%' OR
        D.detl_rem LIKE '%contam%' OR
        D.detl_rem LIKE '%stain%' OR
        D.detl_rem LIKE '%smell%' OR
        D.detl_rem LIKE '%sheen%' OR
        D.detl_rem LIKE '% oil%' OR
        D.detl_rem LIKE '%hydrocarbon%' OR
        D.detl_rem LIKE '%chemical%' OR
        D.detl_rem LIKE '%asbestos%' OR
        
        D.detl_desc LIKE '%odour%' OR
        D.detl_desc LIKE '%contam%' OR
        D.detl_desc LIKE '%stain%' OR
        D.detl_desc LIKE '%smell%' OR
        D.detl_desc LIKE '%sheen%' OR
        D.detl_desc LIKE '% oil%' OR
        D.detl_desc LIKE '%hydrocarbon%' OR
        D.detl_desc LIKE '%chemical%' OR
        D.detl_desc LIKE '%asbestos%'
)

SELECT
    -- QGIS Unique Feature Identifier (Allows clicking/identifying features on map)
    ROW_NUMBER() OVER () AS fid,
    
    U."Source Table",
    U.loca_id AS "Exploratory Hole Location",
    CAST(NULLIF(L.LOCA_NATE, '') AS REAL) AS "Easting",
    CAST(NULLIF(L.LOCA_NATN, '') AS REAL) AS "Northing",
    CAST(NULLIF(L.LOCA_GL, '') AS REAL) AS "Ground Level (mAOD)",
    U.top_m AS "Remark Depth Top (m)",
    U.base_m AS "Remark Depth Base (m)",
    
    -- Dynamic Level calculation: Z = Ground Elevation - Remark Top Depth (Rounded to 2 decimal places)
    ROUND(CAST(NULLIF(L.LOCA_GL, '') AS REAL) - U.top_m, 2) AS "Remark Top Elevation (mAOD)",

    U.description AS "Description",
    U.remarks AS "Comments / Remarks",
    
    -- Geometry mapping column for QGIS SpatiaLite / GeoPackage Engine
    L.geom

FROM UnifiedContam U

-- Join back to the exploratory hole location spatial table to pull coordinates and ground level
LEFT JOIN 
    loca L ON U.loca_id = L.LOCA_ID

ORDER BY 
    U.loca_id, 
    U.top_m, 
    U."Source Table";
