-- ==============================================================================
-- QUERY TITLE       : ERES Stratum Correlation (ERES/GEOL)
-- AUTHOR / EMAIL    : Richard Meredith / richard.meredith@geo-env.co.uk
-- ORGANIZATION      : GeoEnvironmental Consulting Ltd
-- PROJECT / TOOLS   : AGS Tools Project (FOSS)
-- LICENSE           : GNU GPL v3 (GPL-compatible open-source)
-- COMPATIBILITY     : QGIS 3.x (SpatiaLite / GeoPackage SQLite Provider)
-- AGS VERSION       : AGS 4.0.x / 4.1.x
-- SOURCE TABLES     : ERES, GEOL
-- DESCRIPTION       : Correlates environmental laboratory test results (ERES) with their corresponding geological stratum description (GEOL) by dynamically checking if the sample top depth falls between the top and base boundaries of the logged geology records.
-- ==============================================================================
-- ==============================================================================
-- ⚖️ GNU GPL v3 LICENSE & PROFESSIONAL DISCLAIMER 
-- ==============================================================================
-- Copyright (C) 2026 GeoEnvironmental Consulting Ltd
--
-- This SQL query is free software: you can redistribute it and/or modify
-- it under the terms of the GNU General Public License as published by
-- the Free Software Foundation, version 3 of the License.
--
-- This code is distributed WITHOUT ANY WARRANTY; without even the implied 
-- warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
-- GNU General Public License for more details <https://www.gnu.org/licenses/>.
--
-- TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW:
-- 1. All implied terms, conditions, and warranties—including but not limited to 
--    implied terms of SATISFACTORY QUALITY, FITNESS FOR A PARTICULAR PURPOSE, 
--    and non-infringement of intellectual property—are hereby EXCLUDED.
--
-- 2. The author and GeoEnvironmental Consulting Ltd shall not be liable for any 
--    direct, indirect, incidental, or consequential loss or damage (including 
--    but not limited to site engineering errors, financial loss, business 
--    disruption, or data corruption) arising from the use of, or reliance upon, 
--    the outputs generated by this script.
--
-- 3. PROFESSIONAL RESPONSIBILITY (THE 'ENGAGE BRAIN' DIRECTIVE): 
--    This SQL query is a spatial processing tool, not a crystal ball. 
--    It does not replace professional, qualified human interpretation. Users are 
--    respectfully but firmly reminded to engage their brains (specifically ensuring 
--    cognition is in a forward gear) before executing this script or trusting its 
--    outputs. Trusting automated spatial interpolation blindly is a guaranteed 
--    recipe for causing expensive mistakes.
--
-- NOTHING IN THIS DISCLAIMER SHALL LIMIT OR EXCLUDE LIABILITY FOR:
-- (a) Death or personal injury resulting from negligence;
-- (b) Fraud or fraudulent misrepresentation; or
-- (c) Any other liability which cannot be excluded or limited under the laws of 
--     England and Wales.
-- ==============================================================================
SELECT *

-- Main table is ERES (Environmental Results).
FROM
  ERES

-- Left join with the GEOL (Geology) table to pull in soil descriptions.
LEFT JOIN
  GEOL

-- Join conditions to find the specific geology layer that contains the sample depth:
ON
  GEOL.LOCA_ID = ERES.LOCA_ID  -- Match rows where the Location ID from both tables are equal.
  AND CAST(GEOL.GEOL_TOP AS FLOAT) <= CAST(ERES.SAMP_TOP AS FLOAT)  -- Ensure the sample top depth is at or below the top of the geology layer.
  AND CAST(GEOL.GEOL_BASE AS FLOAT) > CAST(ERES.SAMP_TOP AS FLOAT);  -- Ensure the sample top depth is above the base of the geology layer.
